#!/bin/sh -e

export BIN=""
if [ -d "venv" ] ; then
    export BIN="venv/bin/"
fi
export SOURCE_FILES="src/msgpack_asgi tests"

set -x

${BIN}black --check --diff --target-version=py36 $SOURCE_FILES
${BIN}flake8 $SOURCE_FILES
${BIN}mypy $SOURCE_FILES
${BIN}isort --check --diff $SOURCE_FILES
