#!/bin/sh -e

export BIN="venv/bin/"

set -x

python -m venv venv
${BIN}python -m pip install -U pip
${BIN}python -m pip install -r requirements.txt

set +x

echo
echo "Success! You can now activate your virtual environment using:"
echo "source ${BIN}activate"
