#!/bin/sh -e

export BIN=""
if [ -d "venv" ] ; then
    export BIN="venv/bin/"
fi
export SOURCE_FILES="src/msgpack_asgi tests"

set -x

${BIN}autoflake --in-place --recursive $SOURCE_FILES
${BIN}seed-isort-config --application-directories=msgpack_asgi
${BIN}isort $SOURCE_FILES
${BIN}black --target-version=py36 $SOURCE_FILES
